### ISSUE TITLE
5 x slower in RNN

### ISSUE THREAD

**Issue by ghost** [idiap/importance-sampling#3]
Just FYI. I haven´t read the paper yet, but trying to use it out-of-the-box appyling ImportanceTraining to my RNN language model, the training time went from 16 hours to 83 hours... :(
I´ll read the paper and the code later.
Cheers

**Comment by angeloskath** [comment]
Hi,

Thanks for downloading and using and sharing your results.

The time per epoch is expected to increase. You can control the tradeoff with the `presample` keyword argument of the `ImportanceTraining` (and `ApproximateImportanceTraining`) classes. However, the needed epochs are expected to decrease.

For instance, if you set the presample parameter to 2x the batch size the time per epoch is expected to increase by approximately 1.5x (so 24 hours in your case) **but** it is expected that you will need less epochs to achieve the same (or better accuracy).

So I would like to ask you, if you let it run for 16 hours how is the performance? If you instead use the `ApproximateImportanceTraining` class how is the performance? The last experiment in the paper is very similar to what you just did so you can get an idea of what kind of improvement you can expect.

Let me know if you did not have good results (of course if you did as well). Maybe you could also share your model with me so that I can experiment with it on a standard benchmark dataset like PTB.

**Comment by ghost** [comment]
Hi, 
Thanks a lot for the promp answer.  I am in the middle of works in my house so I had to shutdown the system, but I will keep testing your tool and coming back to share the results.
Thanks again.

**Comment by angeloskath** [comment]
Hi, the default presample value has been changed to 256 from 1024 in version 0.3. If you have new results good or bad let me know.
