### ISSUE TITLE
Question regarding maximum variance reduction & speedup

### ISSUE THREAD

**Issue by liaocs2008** [idiap/importance-sampling#31]
Hi,

May I ask how do you calculate the maximum variance reduction 1/b - 1/B and maximum speedup (B+3b)/(3B)?

Thanks!

**Comment by angeloskath** [comment]
Since we subsample from the full dataset the smallest possible variance that can be achieved is the same as using the large batch B to compute the gradient.

Assuming that the backward pass costs twice as much as the forward pass then the total time cost in forward pass per sample units is 3B for using a batch size of B and the cost for importance sampling is B + 3b.

Hence the best possible scenario is to achieve the smallest variance and the speedup would be approximately (B+3b) / (3B).

Cheers,
Angelos

**Comment by liaocs2008** [comment]
Hi Angelos, 

Thanks for the reply!

Could you explain why the maximum variance reduction is 1/b - 1/B? What does 1/b and 1/B mean exactly, percentage?

Moreover, since Eq. 23 suggests that the the difference is always positive, have you considered always sampling in some distribution gi?

**Comment by angeloskath** [comment]
Hi,

I will try to answer in turn.

1. SGD creates a Monte-Carlo estimate of the batch gradient. Let's say that this estimator has variance V. Using a batch size of b which is basically averaging b identical independent estimators results in variance V/b. So the variance of using uniform sampling with a batch size of b is V/b . And because we use a large batch B the best importance sampling can do is V/B. So if we compute the percentage of the variance reduction is (prev_variance - current_variance) / initial_variance = (V/b - V/B)/V = 1/b - 1/B. But I agree with you that it is badly worded and hard to understand.
2. Equation 23 uses the fact that g_i ∝ ||G_i||_2 so we cannot sample from any distribution. Only the optimal one.

**Comment by liaocs2008** [comment]
These make so much sense. Thank you!
